### PR TITLE
Reconnect websockets when they close unexpectedly

### LINKED ISSUE #1057: Problem: Regularly get "write EPIPE" error from Dashboard in Tilt dev env
**Describe the bug**

In the Enduro Tilt dev environment when I load the package list in the Dashboard the page often fails to load a displays a totally blank white screen.  The Dashboard log has the following error messages:

```
VITE v5.4.8  ready in 705 ms

  ➜  Local:   [http://localhost:80/](http://localhost/)
  ➜  Network: use --host to expose
3:32:41 PM [vite] ✨ new dependencies optimized: @vueuse/core, bootstrap/js/dist/tooltip, @vue/reactivity
3:32:41 PM [vite] ✨ optimized dependencies changed. reloading
Reconnecting... Error port-forwarding enduro-dashboard (8080 -> 80): creating stream: Timeout occurred
3:33:19 PM [vite] ws proxy socket error:
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:161:15)
    at writeGeneric (node:internal/stream_base_commons:152:3)
    at Socket._writeGeneric (node:net:954:11)
    at Socket._write (node:net:966:8)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at Socket.ondata (node:internal/streams/readable:1007:22)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
```

**To Reproduce**

1. Start the Tilt dev environment with `tilt up`
2. Add a one or more SIPs to the the Minio "sips" bucket to start processing
3. Open the Enduro Dashboard in a browser window (http://localhost:8080/packages)
4. Click on the "Packages" link on the left side of the screen
5. Page fails to load, and after some time (30s?) the above errors are written the Tilt log for the "enduro-dashboard" resource

**Expected behavior**

The package list should load without errors

**Screenshots**

image

**Additional context**

If I wait a couple of minutes then try to reload http://localhost:8080/packages it usually loads fine.

### PR DESCRIPTION
**Pull request by djjuhasz**
Fixes #1057.

Attempt to reconnect the ingest and storage monitor websockets when the connection is unexpected closed at the server end (e.g. on server restart). My tests so far indicate that this change fixes the problem I've been having with the Dashboard hanging intermittently and throwing Vite "write EPIPE" errors.

### CODE REVIEW

File: dashboard/src/client.ts [hunk 1]
```diff
@@ -48,6 +48,18 @@ function connectIngestMonitor() {
       handleIngestEvent(data.ingestValue);
     }
   };
+  socket.onclose = () => {
+    console.error("Ingest monitor socket closed");
+    setTimeout(() => {
+      console.log("Reconnecting ingest monitor socket...");
+      client.ingest.ingestMonitorRequest().then(() => {
```
Comment (jraddaoui) [inline dashboard/src/client.ts]: I'd consider putting this initial request inside the `connectIngestMonitor` function directly, and the same for storage. It would reduce some duplication, leaving the calls in App.vue just with `client.connectIngestMonitor();` and `client.connectStorageMonitor();` inside the if, and similar here on close.

https://github.com/artefactual-sdps/enduro/blob/main/dashboard/src/App.vue#L19-L24

**Review by jraddaoui — APPROVED** [review]
LGTM @djjuhasz, thanks for looking into this! Just a minor suggestion to reduce duplication.

File: dashboard/src/client.ts (hunk 1 above)
Comment (djjuhasz) [reply dashboard/src/client.ts]: @jraddaoui I don't understand what you mean.  The `connectIngestMonitor()` method is autogenerated, I'm not sure how we would modify the function put the `ingestMonitorRequest()` call "inside" it. :confused:

Comment (djjuhasz) [reply dashboard/src/client.ts]: Oh, I see. `connectIngestMonitor()` isn't auto-generated, `ingestMonitorRequest()` is auto-generated.

**Comment by djjuhasz** [comment]
@jraddaoui I totally rewrote the monitor reconnection logic to include exponential backoff with jitter, and an attempt limit.  I've also moved the ingest and monitor state to Pinia to preserve the WebSocket connections through page updates.  I've also added tests for all of the reconnection logic.

File: dashboard/src/monitor.ts [hunk 2]
```diff
@@ -0,0 +1,180 @@
...
+};
+
+export interface MonitorConnector {
+  dial(): Promise<void>;
+  isConnected(): boolean;
+  getWebSocketURL(url: string): string;
+  close(): void;
+}
+
+export class MonitorConnection {
```
Comment (jraddaoui) [inline dashboard/src/monitor.ts]: I'd make this an abstract class with an abstract dial method and implement `MonitorConnector` directly. That will force all subclasses to implement `MonitorConnector` even if it's forgotten and it will reduce some minor duplication (see below).

```ts
export abstract class MonitorConnection implements MonitorConnector {
  // Existing code.
  
  abstract dial(): Promise<void>;
}
```

File: dashboard/src/monitor.ts [hunk 3]
```diff
@@ -0,0 +1,180 @@
...
+  async connectSocket(url: string): Promise<void> {
+    this.socket = new WebSocket(url);
+
+    this.socket.onopen = () => {
+      console.log(`${this.type} monitor socket connected`);
+    };
+    this.socket.onerror = () => {
+      console.error(`${this.type} monitor socket error`);
+    };
+  }
```
Comment (jraddaoui) [inline dashboard/src/monitor.ts]: With the abstract dial method you could move the `onclose` set up here too:

```ts
connectSocket(url: string): void {
  this.socket = new WebSocket(url);

  this.socket.onopen = () => {
    console.log(`${this.type} monitor socket connected`);
  };
  this.socket.onerror = () => {
    console.error(`${this.type} monitor socket error`);
  };

  // Reconnect on close.
  this.socket.onclose = () => {
    console.error(`${this.type} monitor socket closed, reconnecting...`);
    this.dial();
  };
}
```

File: dashboard/src/monitor.ts [hunk 4]
```diff
@@ -0,0 +1,180 @@
...
+}
+
+export class IngestMonitorConnection
+  extends MonitorConnection
+  implements MonitorConnector
+{
```
Comment (jraddaoui) [inline dashboard/src/monitor.ts]: This will only need to extend MonitorConnection:

```ts
export class IngestMonitorConnection extends MonitorConnection {}
```

File: dashboard/src/monitor.ts [hunk 5]
```diff
@@ -0,0 +1,180 @@
...
+      return client.ingest
+        .ingestMonitorRequest()
+        .then(async () => {
+          return this.connectSocket(this.url).then(() => {
+            if (this.socket) {
+              // Reconnect on close.
+              this.socket.onclose = () => {
+                console.error("ingest monitor socket closed, reconnecting...");
+                this.dial();
+              };
```
Comment (jraddaoui) [inline dashboard/src/monitor.ts]: And this could be removed.

File: dashboard/src/monitor.ts [hunk 6]
```diff
@@ -0,0 +1,180 @@
...
+          throw err;
+        });
+    });
+  }
+}
+
+export class StorageMonitorConnection
+  extends MonitorConnection
+  implements MonitorConnector
+{
```
Comment (jraddaoui) [inline dashboard/src/monitor.ts]: Same.

File: dashboard/src/monitor.ts [hunk 7]
```diff
@@ -0,0 +1,180 @@
...
+      return client.storage
+        .storageMonitorRequest()
+        .then(async () => {
+          return this.connectSocket(this.url).then(() => {
+            if (this.socket) {
+              // Reconnect on close.
+              this.socket.onclose = () => {
+                console.error("storage monitor socket closed, reconnecting...");
+                this.dial();
+              };
```
Comment (jraddaoui) [inline dashboard/src/monitor.ts]: Same.

File: dashboard/src/monitor.ts [hunk 8]
```diff
@@ -0,0 +1,180 @@
...
+  maxAttempts: number;
+  jitterFn: () => number;
+};
+
+export interface MonitorConnector {
+  dial(): Promise<void>;
+  isConnected(): boolean;
+  getWebSocketURL(url: string): string;
+  close(): void;
+}
```
Comment (jraddaoui) [inline dashboard/src/monitor.ts]: Actually, with the abstract class I think we could remove this interface entirely, the `MonitorConnection` class will define the contract.

File: dashboard/src/monitor.ts [hunk 9]
```diff
@@ -0,0 +1,180 @@
...
+
+  close(): void {
+    if (this.socket) {
+      this.socket.onclose = null; // Disable reconnection on close.
+      this.socket.close();
+      this.socket = null;
+    }
+  }
+
+  async connectSocket(url: string): Promise<void> {
```
Comment (jraddaoui) [inline dashboard/src/monitor.ts]: Why is this method async and returning a promise?

```ts
connectSocket(url: string): void {}
```

That would work, right? Then we'll need to update the dial calls:

```ts
this.connectSocket(this.url);
if (this.socket) {}
```

**Review by jraddaoui — CHANGES_REQUESTED** [review]
Thanks @djjuhasz, looks great to me, nice work!

We could simplify a little the monitor classes by using an abstract class, but it's not a huge deal.

File: dashboard/src/monitor.ts (hunk 9 above)
Comment (djjuhasz) [reply dashboard/src/monitor.ts]: I assumed `new Websocket()` would connect asynchronously and return a promise, but it looks like creating the socket is blocking (and pretty much instantaneous), then the `onopen` handler fires asynchronously when the connection is established. :thinking:

When looking this up I found a great example of a web socket client class: https://websocket.org/guides/languages/javascript/.  I wish I'd found that before trying to write this whole class myself. :facepalm:

**Comment by djjuhasz** [comment]
@jraddaoui I think I've addressed all your feedback and this is ready for another look.  I also stopped exporting the "MonitorConnect" class, and changed the `isConnected()` method to an `isConnected` property, following the example of: https://websocket.org/guides/languages/javascript/

**Review by jraddaoui — APPROVED** [review]
Thanks @djjuhasz!
